---
version: "3.7"
services:
  nautobot:
    image: "networktocode/nautobot-plugins:latest"
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    env_file:
      - ".env"
    ports:
      - "8443:8443"
      - "8080:8080"
    restart: "unless-stopped"
