---
language: "python"
python:
- "3.7"
services:
- "docker"
# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
before_script:
- "pip install yamllint"

script:
- "yamllint ."
