[tool.poetry]
name = "nautobot-docker-compose"
version = "0.1.1"
description = ""
authors = ["John Doe <johndoe@mail.com>"]

[tool.poetry.dependencies]
python = ">=3.9.2,<3.13"
nautobot = "2.4.6"

# nautobot-example-plugin = {path = "plugins/plugin_example", develop = true}


[tool.poetry.dev-dependencies]
invoke = "*"
toml = "*"

[tool.poetry.group.dev.dependencies]
mydocstring = "^0.2.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
