---
services:
  nautobot:
    #  command: "nautobot-server runserver 0.0.0.0:8443"
    command: ["uwsgi", "--ini", "/opt/nautobot/uwsgi.ini"]
    ports:
      - "8443:8443"
    volumes:
      - "../config/nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../jobs:/opt/nautobot/jobs"
      - "./Certificate/fullchain1.pem:/etc/ssl/nautobot/fullchain1.pem" 
      - "./Certificate/privkey1.pem:/etc/ssl/nautobot/privkey1.pem"

    healthcheck:
      interval: "30s"
      timeout: "10s"
      start_period: "60s"
      retries: 3
      test: ["CMD", "true"]  # Due to layering, disable: true won't work. Instead, change the test
  celery_worker:
    volumes:
      - "../config/nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../jobs:/opt/nautobot/jobs"
