---
version: "3.8"
services:
  db:
    image: "postgres:13-alpine"
    env_file:
      - "local.env"
      - "creds.env"
    command:
      - "-c"
      - "max_connections=1000"
    volumes:
      # - "./nautobot.sql:/tmp/nautobot.sql"
      - "postgres_data:/var/lib/postgresql/data"
volumes:
  postgres_data: {}
