---
- name: Test creating a computed field in Nautobot
  hosts: localhost
  gather_facts: false

  vars:
    nautobot_url: "https://machine17.ac.tamu.edu:8443"
    nautobot_api_token: "0123456789abcdef0123456789abcdef01234567"


    payload:
      content_type: "dcim.interface"
      key: "device_interface_test"
      label: "Device - Interface (Test)"
      description: "Testing version of device-interface field for validation"
      template: "{{ '{{ obj.device.name }} - {{ obj.name }}' }}"
      fallback_value: ""
      weight: 100
      advanced_ui: false

  tasks:
    - name: Create computed field using Nautobot API
      ansible.builtin.uri:
        url: "{{ nautobot_url }}/api/extras/computed-fields/"
        method: POST
        headers:
          Authorization: "Token {{ nautobot_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ payload | to_json }}"
        status_code: 201
        validate_certs: false
