---
name: "CI"
on:
  - "push"
  - "pull_request"

jobs:
  yamllint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        id: "python-setup"
        with:
          python-version: "3.9"
      - name: "Install yamllint"
        run: "pip install yamllint"
      - name: "Run yamllint"
        run: "yamllint ."
